✨ QQ 适配器部分实现
MountainDash/nonebot-plugin-send-anything-anywhere pull request #121
Opened 2023-11-24 15:53 UTC by mobyw

- 使用独立的 Open Target，字段类型修改为 `int`
- 实现了群聊和私聊的 target 提取
- `extract_target` 可传入 bot
- 对应的测试

2023-11-24 15:55 UTC, Dreamail commented
草我还在rebase呢，突然就被抢先了（

2023-11-24 15:57 UTC, Dreamail commented
不对，openid target main已经有了，不要自己再加一个

2023-11-27 12:39 UTC, felinae98 requested changes

2023-11-27 12:39 UTC, felinae98 commented on nonebot_plugin_saa/registries/platform_send_target.py
> +ExtractorOpenId = Callable[[Event, Bot], PlatformTarget]
```suggestion
ExtractorWithBotSpecifier = Callable[[Event, Bot], PlatformTarget]
```

2023-11-27 12:39 UTC, felinae98 commented on nonebot_plugin_saa/registries/platform_send_target.py
> +            if "bot" in inspect.signature(extractor_map[event_type]).parameters.keys():
这里检查 param 的数量会不会好一点，如果未来有人写的 extractor 的形参不叫 bot 可能会在这里被坑很久

2023-11-28 01:59 UTC, felinae98 commented on tests/test_qq.py
> +async def test_extract_target(app: App):
这个地方测试一下 SaaTarget 这个 nonebot dependency 能不能正确提取到 target 吧

2023-11-28 05:03 UTC, felinae98 commented on tests/test_qq.py
> +        assert isinstance(target, TargetQQGuildChannel)
check 一下 bot_id

2023-11-28 05:16 UTC, merged