📝 完善使用文档
MountainDash/nonebot-plugin-send-anything-anywhere pull request #133
Opened 2024-01-20 15:52 UTC by AzideCupric

2024-01-20 16:22 UTC, BalconyJH commented on docs/docs/usage/01-quickstart.md
> +    response: str = "柳州: 🌦   +14°C"# 能返回文本的天气API
这里的注释使用类似这样的格式可能会有助于提高可读性
![772c1a561a8625c0f553a28042e5e5e0](https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/assets/73932916/f3d066f6-3eb5-42af-951b-e5a4bab89d70)

2024-01-20 16:38 UTC, KomoriDev requested changes

2024-01-20 16:38 UTC, KomoriDev commented on docs/docs/usage/02-message-build.md
> +SAA 并不提供 user_id 的获取方法，因此需要自行获取。
加个例子？
```suggestion
SAA 并不提供 user_id 的获取方法，因此需要自行获取。
```python
from nonebot.log import logger
from nonebot.adapters import Event

@matcher.handle()
async def handle(event: Event):
    user_id = event.get_user_id()
    logger.info(f"USER: {user_id}")
```
```

2024-01-20 16:38 UTC, KomoriDev commented on docs/docs/usage/03-send.md
> +被动发送是指用户方触发消息发送，例如用户发送一条消息，然后Bot进行回复。
`Bot` 前后应空格

2024-01-20 16:38 UTC, KomoriDev commented on docs/docs/usage/03-send.md
> +可以发现其实 `send_to` 方法允许不提供 bot参数，只提供 PlatformTarget，这会让SAA自动按照 PlatformTarget 的具体实例按照一定的规则选择Bot进行发送。
- `bot` 首字母大写
- `Bot`、`SAA` 前后应空格

2024-01-20 16:38 UTC, KomoriDev commented on docs/docs/usage/03-send.md
>  在使用saa的主动发送消息功能
`saa` 应大写、前后空格

2024-01-20 16:38 UTC, KomoriDev commented on docs/docs/usage/03-send.md
>  在使用saa的主动发送消息功能
125、126行一样

2024-01-20 16:38 UTC, KomoriDev commented on docs/docs/usage/03-send.md
> +在插件加载时调用`enable_auto_select_bot`函数即可开启这个功能。
好像所有的 `enable_auto_select_bot` 前后都缺少空格

2024-01-20 16:40 UTC, AzideCupric commented on docs/docs/usage/03-send.md
> +可以发现其实 `send_to` 方法允许不提供 bot参数，只提供 PlatformTarget，这会让SAA自动按照 PlatformTarget 的具体实例按照一定的规则选择Bot进行发送。
> * `bot` 首字母大写

这里的 `bot` 是 send_to 的形参(

2024-01-20 16:41 UTC, AzideCupric commented on docs/docs/usage/03-send.md
> +在插件加载时调用`enable_auto_select_bot`函数即可开启这个功能。
这个是之前写的了

2024-01-20 17:02 UTC, KomoriDev commented on docs/docs/usage/03-send.md
> +可以发现其实 `send_to` 方法允许不提供 bot参数，只提供 PlatformTarget，这会让SAA自动按照 PlatformTarget 的具体实例按照一定的规则选择Bot进行发送。
没细看😰
但少空格该没错吧（逃

2024-01-23 14:15 UTC, felinae98 commented on docs/docs/usage/01-quickstart.md
> +> 还没有？请参考 [nOneboT的快速上手](https://nonebot.dev/docs/next/quick-start) 章节。
nOneboT?

2024-01-23 14:44 UTC, merged